#!/usr/bin/perl -w
use strict;
  
#First to count the characteristic value of varant type in each chromosome, we initialize an output file called 'Output.txt', and print header (we include 6 columns titled: 'chromosome', 'SV Type', 'Total', 'Mean read count', 'Mean score', and 'Mean size')to the file you create.
my $output = "Output.txt";
open OU, ">$output";
print OU "chromosome\tSV type\tTotal\tMean read count\tMean score\tMean size\n";

#Define count variable
my $count;

#Define array and transfer the files into this array
open $count, '<', "$ARGV[0]";
my @array = <$count>;

#Setup a for loop to loop through the individual chromosome files and make sure whether all the files exists in current directory, if not, an error message will be printed.
for my $i (@array){
	chomp $i;
	if (-e $i){

        } else {

                print "ERROR, $i file do not exist\n";
        }
}


#Setup a for loop to calculate the information of each chromosome. The first operation inside of loop is to extract each file name from the list of files,once we have successfully extracted the filename, perform a sanity check to ensure that each file exists and is not empty. If any files do not exist or are empty, an error message will be printed and abort the script.
for my $i (@array){
	chomp $i;
	my %total;
	my %mean_read_count;
	my %mean_score;
	my %mean_size;
	my $file = $i;
	open IN, $file or die "lacking $file file\n";
	while (<IN>){
		chomp;
		if ($_ =~ /^#/){next;}
		my @array_info = split /\t/,$_;

#Perform four main calculations per chromosome for each type of structural variant. First, isolate the infomation in the correct column that specifies the type of SV in the input file. Then use regular expressions to separate the five possible types (SVs, INS, DEL, INV, ITX/CTX)of SVs in this datafile. Finally, get the statistics information of variation number, supporting supporting reads, mean score and mean size of each SV types.
		if ($array_info[6] =~ /((INS|DEL|INV|ITX|CTX))/){
			my $SV_type = $1;
			if (exists $total{$SV_type}){
				$total{$SV_type} += 1;

			} else {

				$total{$SV_type} = 1;

			}

			if (exists $mean_read_count{$SV_type}){

				$mean_read_count{$SV_type} += $array_info[9];
			} else {

				$mean_read_count{$SV_type} = $array_info[9];

			}
				
 	         	if (exists $mean_score{$SV_type}){

                                $mean_score{$SV_type} += $array_info[8];
                        } else {

                                $mean_score{$SV_type} = $array_info[8];

                        }

			my $size = $array_info[1] - $array_info[4];
			if ($size < 0){ $size = -$size;}
			if (exists $mean_size{$SV_type}){
				$mean_size{$SV_type} += $size;
				
			} else {


				$mean_size{$SV_type} = 0;
			}
			

		}	
	

	}

#calculate the mean value of reads, score and size for each type of SV (extra the Chromosome number and remove the file name as well as suffix). 
#print in specific format.
	for my $SV ("INS","DEL","INV","ITX","CTX"){
 		$i =~ s/bdmax//;
		$i =~ s/.ctx//; 
		if (!exists $total{$SV}){next;}
		my $mean_read = $mean_read_count{$SV} / $total{$SV};
		my $mean_score = $mean_score{$SV} / $total{$SV};
		my $mean_size = $mean_size{$SV} / $total{$SV};
		print OU "$i\t$SV\t$total{$SV}\t$mean_read\t$mean_score\t$mean_size\n";

	}

}
 
#make the script to sleep 3 second so that output could write into the memory of linux, otherwise, the next step could not read this summary correctlly. 
`sleep 3`;

#calculate the information of all the chromosome. Store four calculations in variables so that we can print them to the output file we made above. 
my $total_sum = 0;
my $read_sum = 0;
my $score_sum =0;
my $size_sum = 0;
my $line_sum =0;

my $input = "Output.txt";
open AL, $input;
while (<AL>){
	chomp;
	if (/^chr/){next;}
	my @all = split /\s+/,$_;
	$line_sum += 1;
	$total_sum += $all[2];
	$read_sum += $all[3];	
	$score_sum += $all[4];
	$size_sum += $all[5];	
}

#print "$read_sum\t$total\t$score_sum\t$size_sum\n";

my $all_mean_total = $total_sum/$line_sum;
my $all_mean_read = $read_sum/$line_sum;
my $all_socre = $score_sum/$line_sum;
my $all_size = $size_sum/$line_sum;


print OU "All\tALL\t$all_mean_total\t$all_mean_read\t$all_socre\t$all_size\n";
close OU;
